### ISSUE TITLE
Replacing Compare.links function with accuracy (ACC)

### ISSUE THREAD

**Issue by anubhav3** [anubhav3/foodwebs#1]
We could replace with the Compare.links function with accuracy (ACC) (https://en.wikipedia.org/wiki/Confusion_matrix). ACC would take into account overlap of both links and no links in the predicted and observed matrix.

**Comment by opetchey** [comment]
I implemented this in the dev_accuracy branch and it seems to work.
Now a, ai, aj, and r.b are all estimated at the same time with the optim function, so its a lot neater.
I also tidied the code.
Should be much nicer for you to work on now (sorry for not doing this before).
If you like to work on this simpler dev_accuracy version, please merge the dev_accuracy branch into master.
All the best
Owen

**Comment by anubhav3** [comment]
Thank you! I would say it was good that it was not done before as this gave me a chance to figure out things myself. 
I have merged the dev_accuracy branch into master.
