### ISSUE TITLE
Why are we using max before "(which..."? Could you help me out?

### ISSUE THREAD

**Issue by anubhav3** [anubhav3/foodwebs#4]
https://github.com/anubhav3/foodwebs/blob/4534be649e96c4a299118cfbb351bb3cb58efeb0/code/ADBM.functions.r#L86

**Comment by opetchey** [comment]
I think it is in case the maximum value appears twice in the vector, as we must only have the position of one maximum in dj.

**Comment by anubhav3** [comment]
Thanks, got it.
So, let's say if we have two values of k (say 2 and 11). Here, we will be taking dj as 11. Therefore, we are moving more to a generalist type of species.

**Comment by opetchey** [comment]
Yes, more or less. Though I think the values would have to be consecutive. I.e. 
`which(cumulative.profit==max(cumulative.profit))` could be (3, 4) and so dj would be set to the max of these (4).
